---

path:
  root: /home/kyuholee/SPD_ver_3
  db: ${path.root}/E_database
  config_path: ${path.root}/A_config
  result_path: ${path.root}/F_results

data:
  timeframe:
    - '5m'
    - '15m'
    - '30m'
    - '1h'
  forward_window: 
    - 5
    - 4
    - 3
    - 2

...