CNN_LSTM: {}
CNN_transformer: {}
LSTM:
  dropout: 0.1
  n_class: 3
  nhid: 256
  ninp: 29
  nlayers: 8
backward: 100
batch: 128
coin_number: 40
commission_fee: 0.001
epoch: 20
forward: 5
lr: 1.40625e-07
model: transformer
name: exp_5
num: 7
quantile: 0.85
scheduler: null
sliding: 1
stop_loss: 0.01
test:
  end:
  - 2023
  - 9
  - 1
  - 10
  size: 5000
  start:
  - 2023
  - 6
  - 1
  - 10
timestamp: 5m
train:
  end:
  - 2022
  - 7
  - 1
  - 10
  size: 100000
  start:
  - 2020
  - 5
  - 1
  - 10
transformer:
  attn_pdrop: 0.1
  embd_pdrop: 0.1
  input_dim: 29
  n_class: 3
  nff: 2048
  nhead: 32
  nhid_tran: 512
  nlayers_transformer: 8
  resid_pdrop: 0.1
validation:
  end:
  - 2023
  - 2
  - 1
  - 10
  size: 5000
  start:
  - 2022
  - 9
  - 1
  - 10
