CNN_LSTM: {}
CNN_transformer: {}
LSTM: {}
backward: 100
batch: 128
coin_number: 10
commission_fee: 0.001
epoch: 30
forward: 5
lr: 4.5e-06
model: transformer
name: exp_2
num: 1
quantile: 0.85
scheduler:
  gamma: 0.5
  milestones:
  - 10
  - 20
  name: MultiStepLR
sliding: 1
stop_loss: 0.01
test:
  end:
  - 2023
  - 4
  - 1
  - 10
  size: 5000
  start:
  - 2023
  - 3
  - 1
  - 10
timestamp: 5m
train:
  end:
  - 2022
  - 7
  - 1
  - 10
  size: 50000
  start:
  - 2020
  - 5
  - 1
  - 10
transformer:
  attn_pdrop: 0.1
  embd_pdrop: 0.1
  input_dim: 29
  n_class: 3
  nff: 1024
  nhead: 16
  nhid_tran: 256
  nlayers_transformer: 8
  resid_pdrop: 0.1
validation:
  end:
  - 2023
  - 2
  - 1
  - 10
  size: 5000
  start:
  - 2022
  - 9
  - 1
  - 10
